[package]
name = "proxy-limiter-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
base64 = "0.22.0"
governor = "0.6.3"
serde_json = "1.0.114"
